/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.82
 * Generated at: 2023-11-05 08:58:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import data.vo.*;
import java.util.ArrayList;

public final class Admin_005fmode2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("data.vo");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

request.setCharacterEncoding("utf-8");

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"utf-8\" />\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />\n");
      out.write("<title>서원대학교</title>\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/Main.css\" />\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/MyPage.css\" />\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/LoginPopup.css\" />\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/css/all.min.css\"\n");
      out.write("	integrity=\"sha512-rqQltXRuHxtPWhktpAZxLHUVJ3Eombn3hvk9PHjV/N5DMUYnzKPC1i3ub0mEXgFzsaZNeJcoE0YHq0j/GFsdGg==\"\n");
      out.write("	crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\n");
      out.write("<script src=\"https://kit.fontawesome.com/46fda0e82e.js\"\n");
      out.write("	crossorigin=\"anonymous\"></script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	");

	ArrayList<Matching_criteria_VO> match = (ArrayList) request.getAttribute("match");
	ArrayList<Professor_weight_VO> weight = (ArrayList) request.getAttribute("weight");
	ArrayList<Diagnosis_criteria_VO> level = (ArrayList) request.getAttribute("level");
	
      out.write('\n');
      out.write('\n');
      out.write('	');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "TopArea.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("	<main class=\"main_contents\">\n");
      out.write("		<div class=\"contents\">\n");
      out.write("			<section class=\"nav-contents\">\n");
      out.write("				<div class=\"nav-inner\">\n");
      out.write("					<ul class=\"nav-list\">\n");
      out.write("						<li class=\"l-setting\"><a class=\"btnSetting\">관리 설정</a></li>\n");
      out.write("				</div>\n");
      out.write("			</section>\n");
      out.write("			<div class=\"contents-info show\">\n");
      out.write("				<section class=\"section_marea\">\n");
      out.write("				\n");
      out.write("					<form action=\"/Project_NCP/AdminMode?action=weightSet\"\n");
      out.write("						method=\"post\">\n");
      out.write("						<div class=\"info_text_area\">\n");
      out.write("							<img\n");
      out.write("								src=\"https://semsplus.seowon.ac.kr/contents/images/client/sub/icon_tit_lg.png\" />\n");
      out.write("							<h3 class=\"info_text\">가중치 설정</h3>\n");
      out.write("						</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("						<div class=\"base_info_table\">\n");
      out.write("							<table>\n");
      out.write("\n");
      out.write("								<colgroup>\n");
      out.write("									<col style=\"width: 25%;\">\n");
      out.write("									<col style=\"width: 25%;\">\n");
      out.write("									<col style=\"width: 50%;\">\n");
      out.write("								</colgroup>\n");
      out.write("\n");
      out.write("								<tbody>\n");
      out.write("									<tr>\n");
      out.write("										<th colspan=\"3\">지도 교수 진로개발준비도 평가를 통합점수에 반영하기 위한 가중치 설정</th>\n");
      out.write("									</tr>\n");
      out.write("									<tr>\n");
      out.write("										<th>영역별 평가 척도 (수준)</th>\n");
      out.write("										<th>기존 가중치</th>\n");
      out.write("										<th>신규 가중치</th>\n");
      out.write("									</tr>\n");
      out.write("									<tr>\n");
      out.write("										<td>매우 그렇다(5점)</td>\n");
      out.write("										<td><input readonly=\"readonly\" type=\"text\"\n");
      out.write("											value=");
      out.print(weight.get(4).getWeight());
      out.write("></td>\n");
      out.write("										<td><input type=\"number\" step=\"0.01\"\n");
      out.write("											placeholder=\"신규 가중치를 입력하세요\" onfocus=\"this.placeholder=''\"\n");
      out.write("											onblur=\"this.placeholder='신규 가중치를 입력하세요' \" name=\"setweight\"></td>\n");
      out.write("									</tr>\n");
      out.write("\n");
      out.write("									<tr>\n");
      out.write("										<td>그렇다(4점)</td>\n");
      out.write("										<td><input readonly=\"readonly\" name=\"default_weight\"\n");
      out.write("											type=\"text\" value=");
      out.print(weight.get(3).getWeight());
      out.write("></td>\n");
      out.write("										<td><input type=\"number\" step=\"0.01\"\n");
      out.write("											placeholder=\"신규 가중치를 입력하세요\" onfocus=\"this.placeholder=''\"\n");
      out.write("											onblur=\"this.placeholder='신규 가중치를 입력하세요' \" name=\"setweight\"></td>\n");
      out.write("									</tr>\n");
      out.write("\n");
      out.write("									<tr>\n");
      out.write("										<td>보통(3점)</td>\n");
      out.write("										<td><input readonly=\"readonly\" name=\"default_weight\"\n");
      out.write("											type=\"text\" value=");
      out.print(weight.get(2).getWeight());
      out.write("></td>\n");
      out.write("										<td><input type=\"number\" step=\"0.01\"\n");
      out.write("											placeholder=\"신규 가중치를 입력하세요\" onfocus=\"this.placeholder=''\"\n");
      out.write("											onblur=\"this.placeholder='신규 가중치를 입력하세요' \" name=\"setweight\"></td>\n");
      out.write("									</tr>\n");
      out.write("\n");
      out.write("									<tr>\n");
      out.write("										<td>그렇지 않다(2점)</td>\n");
      out.write("										<td><input readonly=\"readonly\" name=\"default_weight\"\n");
      out.write("											type=\"text\" value=");
      out.print(weight.get(1).getWeight());
      out.write("></td>\n");
      out.write("										<td><input type=\"number\" step=\"0.01\"\n");
      out.write("											placeholder=\"신규 가중치를 입력하세요\" onfocus=\"this.placeholder=''\"\n");
      out.write("											onblur=\"this.placeholder='신규 가중치를 입력하세요' \" name=\"setweight\"></td>\n");
      out.write("									</tr>\n");
      out.write("\n");
      out.write("									<tr>\n");
      out.write("										<td>매우 그렇지 않다(1점)</td>\n");
      out.write("										<td><input readonly=\"readonly\" name=\"default_weight\"\n");
      out.write("											type=\"text\" value=");
      out.print(weight.get(0).getWeight());
      out.write("></td>\n");
      out.write("										<td><input type=\"number\" step=\"0.01\"\n");
      out.write("											placeholder=\"신규 가중치를 입력하세요\" onfocus=\"this.placeholder=''\"\n");
      out.write("											onblur=\"this.placeholder='신규 가중치를 입력하세요' \" name=\"setweight\"></td>\n");
      out.write("									</tr>\n");
      out.write("\n");
      out.write("								</tbody>\n");
      out.write("							</table>\n");
      out.write("						</div>\n");
      out.write("						<div class=\"setBtnDiv\">\n");
      out.write("							<input type=\"submit\" class=\"level_saveBtn\" value=\"저장\"> <input\n");
      out.write("								type=\"submit\" class=\"level_exitBtn\" value=\"취소\">\n");
      out.write("						</div>\n");
      out.write("					</form>\n");
      out.write("				</section>\n");
      out.write("\n");
      out.write("				<section class=\"section_marea\">\n");
      out.write("					<form action=\"/Project_NCP/AdminMode?action=matchSet\" method=\"post\">\n");
      out.write("						<div class=\"info_text_area\">\n");
      out.write("							<img\n");
      out.write("								src=\"https://semsplus.seowon.ac.kr/contents/images/client/sub/icon_tit_lg.png\" />\n");
      out.write("							<h3 class=\"info_text\">매칭 비율 설정</h3>\n");
      out.write("						</div>\n");
      out.write("						<div class=\"match tbl_fixed match_row\">\n");
      out.write("							<table>\n");
      out.write("								<colgroup>\n");
      out.write("									<col style=\"width: 20%;\">\n");
      out.write("									<col style=\"width: 10%;\">\n");
      out.write("									<col style=\"width: 10%;\">\n");
      out.write("									<col style=\"width: 10%;\">\n");
      out.write("									<col style=\"width: 10%;\">\n");
      out.write("									<col style=\"width: 10%;\">\n");
      out.write("									<col style=\"width: 10%;\">\n");
      out.write("									<col style=\"width: 20%;\">\n");
      out.write("								</colgroup>\n");
      out.write("								<tbody>\n");
      out.write("									<tr>\n");
      out.write("										<th colspan=\"8\">진단영역-우리대학 진로취업 역량 매칭 비율 설정</th>\n");
      out.write("									</tr>\n");
      out.write("									<tr>\n");
      out.write("										<th></th>\n");
      out.write("										<th>자기이해</th>\n");
      out.write("										<th>전공직업정보</th>\n");
      out.write("										<th>진로<br>결정 확신도\n");
      out.write("										</th>\n");
      out.write("										<th>의사<br>결정 자신감\n");
      out.write("										</th>\n");
      out.write("										<th>관계 활용도</th>\n");
      out.write("										<th>구직 준비도</th>\n");
      out.write("										<th></th>\n");
      out.write("									</tr>\n");
      out.write("									<tr>\n");
      out.write("										<th>진로취업 역량 <br>(단계)\n");
      out.write("										</th>\n");
      out.write("										<th></th>\n");
      out.write("										<th></th>\n");
      out.write("										<th></th>\n");
      out.write("										<th></th>\n");
      out.write("										<th></th>\n");
      out.write("										<th></th>\n");
      out.write("										<th>합계</th>\n");
      out.write("									</tr>\n");
      out.write("									<tr>\n");
      out.write("										<th>자기이해</th>\n");
      out.write("										");

										for (int i = 0; i <= 5; i++) {
										
      out.write("\n");
      out.write("										<td><input name=\"setMatch\"\n");
      out.write("											value=");
      out.print(match.get(i).getMatching_rate());
      out.write("></td>\n");
      out.write("										");

										}
										
      out.write("\n");
      out.write("										<td>");
      out.print((int) (match.get(0).getMatching_rate() + match.get(1).getMatching_rate() + match.get(2).getMatching_rate()
		+ match.get(3).getMatching_rate() + match.get(4).getMatching_rate() + match.get(5).getMatching_rate()));
      out.write("%</td>\n");
      out.write("									</tr>\n");
      out.write("\n");
      out.write("									<tr>\n");
      out.write("										<th>진로탐색</th>\n");
      out.write("										");

										for (int i = 6; i <= 11; i++) {
										
      out.write("\n");
      out.write("										<td><input name=\"setMatch\"\n");
      out.write("											value=");
      out.print(match.get(i).getMatching_rate());
      out.write("></td>\n");
      out.write("										");

										}
										
      out.write("\n");
      out.write("										<td>");
      out.print((int) (match.get(6).getMatching_rate() + match.get(7).getMatching_rate() + match.get(8).getMatching_rate()
		+ match.get(9).getMatching_rate() + match.get(10).getMatching_rate() + match.get(11).getMatching_rate()));
      out.write("%</td>\n");
      out.write("									</tr>\n");
      out.write("\n");
      out.write("									<tr>\n");
      out.write("										<th>진로결정</th>\n");
      out.write("										");

										for (int i = 12; i <= 17; i++) {
										
      out.write("\n");
      out.write("										<td><input name=\"setMatch\"\n");
      out.write("											value=");
      out.print(match.get(i).getMatching_rate());
      out.write("></td>\n");
      out.write("										");

										}
										
      out.write("\n");
      out.write("										<td>");
      out.print((int) (match.get(12).getMatching_rate() + match.get(13).getMatching_rate() + match.get(14).getMatching_rate()
		+ match.get(15).getMatching_rate() + match.get(16).getMatching_rate() + match.get(17).getMatching_rate()));
      out.write("%</td>\n");
      out.write("									</tr>\n");
      out.write("\n");
      out.write("									<tr>\n");
      out.write("										<th>진로설계</th>\n");
      out.write("										");

										for (int i = 18; i <= 23; i++) {
										
      out.write("\n");
      out.write("										<td><input name=\"setMatch\"\n");
      out.write("											value=");
      out.print(match.get(i).getMatching_rate());
      out.write("></td>\n");
      out.write("										");

										}
										
      out.write("\n");
      out.write("										<td>");
      out.print((int) (match.get(18).getMatching_rate() + match.get(19).getMatching_rate() + match.get(20).getMatching_rate()
		+ match.get(21).getMatching_rate() + match.get(22).getMatching_rate() + match.get(23).getMatching_rate()));
      out.write("%</td>\n");
      out.write("									</tr>\n");
      out.write("\n");
      out.write("									<tr>\n");
      out.write("										<th>경력개발</th>\n");
      out.write("										");

										for (int i = 24; i <= 29; i++) {
										
      out.write("\n");
      out.write("										<td><input name=\"setMatch\"\n");
      out.write("											value=");
      out.print(match.get(i).getMatching_rate());
      out.write("></td>\n");
      out.write("										");

										}
										
      out.write("\n");
      out.write("										<td>");
      out.print((int) (match.get(24).getMatching_rate() + match.get(25).getMatching_rate() + match.get(26).getMatching_rate()
		+ match.get(27).getMatching_rate() + match.get(28).getMatching_rate() + match.get(29).getMatching_rate()));
      out.write("%</td>\n");
      out.write("									</tr>\n");
      out.write("\n");
      out.write("									<tr>\n");
      out.write("										<th>실무역량</th>\n");
      out.write("										");

										for (int i = 30; i <= 35; i++) {
										
      out.write("\n");
      out.write("										<td><input name=\"setMatch\"\n");
      out.write("											value=");
      out.print(match.get(i).getMatching_rate());
      out.write("></td>\n");
      out.write("										");

										}
										
      out.write("\n");
      out.write("										<td>");
      out.print((int) (match.get(30).getMatching_rate() + match.get(31).getMatching_rate() + match.get(32).getMatching_rate()
		+ match.get(33).getMatching_rate() + match.get(34).getMatching_rate() + match.get(35).getMatching_rate()));
      out.write("%</td>\n");
      out.write("									</tr>\n");
      out.write("\n");
      out.write("									<tr>\n");
      out.write("										<th>맞춤취업</th>\n");
      out.write("										");

										for (int i = 36; i <= 41; i++) {
										
      out.write("\n");
      out.write("										<td><input name=\"setMatch\"\n");
      out.write("											value=");
      out.print(match.get(i).getMatching_rate());
      out.write("></td>\n");
      out.write("										");

										}
										
      out.write("\n");
      out.write("										<td>");
      out.print((int) (match.get(36).getMatching_rate() + match.get(37).getMatching_rate() + match.get(38).getMatching_rate()
		+ match.get(39).getMatching_rate() + match.get(40).getMatching_rate() + match.get(41).getMatching_rate()));
      out.write("%</td>\n");
      out.write("									</tr>\n");
      out.write("\n");
      out.write("									<tr>\n");
      out.write("										<th>구직활동</th>\n");
      out.write("										");

										for (int i = 42; i <= 47; i++) {
										
      out.write("\n");
      out.write("										<td><input name=\"setMatch\"\n");
      out.write("											value=");
      out.print(match.get(i).getMatching_rate());
      out.write("></td>\n");
      out.write("										");

										}
										
      out.write("\n");
      out.write("										<td>");
      out.print((int) (match.get(42).getMatching_rate() + match.get(43).getMatching_rate() + match.get(44).getMatching_rate()
		+ match.get(45).getMatching_rate() + match.get(46).getMatching_rate() + match.get(47).getMatching_rate()));
      out.write("%</td>\n");
      out.write("									</tr>\n");
      out.write("								</tbody>\n");
      out.write("							</table>\n");
      out.write("						</div>\n");
      out.write("						<div class=\"setBtnDiv\">\n");
      out.write("							<input type=submit class=\"level_saveBtn\" value=\"저장\"> <input\n");
      out.write("								type=submit class=\"level_exitBtn\" value=\"취소\">\n");
      out.write("						</div>\n");
      out.write("					</form>\n");
      out.write("				</section>\n");
      out.write("\n");
      out.write("\n");
      out.write("				<seciont>\n");
      out.write("				<form action=\"/Project_NCP/AdminMode?action=setLevel\" method=\"post\">\n");
      out.write("					<div class=\"match tbl_fixed match_row\">\n");
      out.write("						<table>\n");
      out.write("							<tbody>\n");
      out.write("								<tr>\n");
      out.write("									<th colspan=\"8\">우리대학 진로취업 역량별 준비수준 진단 기준 설정</th>\n");
      out.write("								</tr>\n");
      out.write("								<tr>\n");
      out.write("\n");
      out.write("									<th rowspan=\"2\">진로취업역량<br>(단계)\n");
      out.write("									</th>\n");
      out.write("									<th rowspan=\"2\">최대점수</th>\n");
      out.write("									<th colspan=\"2\">높음</th>\n");
      out.write("\n");
      out.write("									<th colspan=\"2\">보통</th>\n");
      out.write("\n");
      out.write("									<th colspan=\"2\">낮음</th>\n");
      out.write("\n");
      out.write("								</tr>\n");
      out.write("								<tr>\n");
      out.write("									<th>최대</th>\n");
      out.write("									<th>최소</th>\n");
      out.write("									<th>최대</th>\n");
      out.write("									<th>최소</th>\n");
      out.write("									<th>최대</th>\n");
      out.write("									<th>최소</th>\n");
      out.write("								</tr>\n");
      out.write("								<tr>\n");
      out.write("									<th>자기이해</th>\n");
      out.write("									<td>");
      out.print(level.get(0).getHigh_max());
      out.write("</td>\n");
      out.write("									<td><input name=\"setLevel\"\n");
      out.write("										value=");
      out.print(level.get(0).getHigh_max());
      out.write("></td>\n");
      out.write("									<td><input name=\"setLevel\"\n");
      out.write("										value=");
      out.print(level.get(0).getHigh_min());
      out.write("></td>\n");
      out.write("									<td><input name=\"setLevel\"\n");
      out.write("										value=");
      out.print(level.get(0).getNormal_max());
      out.write("></td>\n");
      out.write("									<td><input name=\"setLevel\"\n");
      out.write("										value=");
      out.print(level.get(0).getNormal_min());
      out.write("></td>\n");
      out.write("									<td><input name=\"setLevel\"\n");
      out.write("										value=");
      out.print(level.get(0).getLow_max());
      out.write("></td>\n");
      out.write("									<td><input name=\"setLevel\"\n");
      out.write("										value=");
      out.print(level.get(0).getLow_min());
      out.write("></td>\n");
      out.write("								</tr>\n");
      out.write("\n");
      out.write("								<tr>\n");
      out.write("									<th>진로탐색</th>\n");
      out.write("									<td>");
      out.print(level.get(1).getHigh_max());
      out.write("</td>\n");
      out.write("									<td><input name=\"setLevel\"\n");
      out.write("										value=");
      out.print(level.get(1).getHigh_max());
      out.write("></td>\n");
      out.write("									<td><input name=\"setLevel\"\n");
      out.write("										value=");
      out.print(level.get(1).getHigh_min());
      out.write("></td>\n");
      out.write("									<td><input name=\"setLevel\"\n");
      out.write("										value=");
      out.print(level.get(1).getNormal_max());
      out.write("></td>\n");
      out.write("									<td><input name=\"setLevel\"\n");
      out.write("										value=");
      out.print(level.get(1).getNormal_min());
      out.write("></td>\n");
      out.write("									<td><input name=\"setLevel\"\n");
      out.write("										value=");
      out.print(level.get(1).getLow_max());
      out.write("></td>\n");
      out.write("									<td><input name=\"setLevel\"\n");
      out.write("										value=");
      out.print(level.get(1).getLow_min());
      out.write("></td>\n");
      out.write("								</tr>\n");
      out.write("\n");
      out.write("								<tr>\n");
      out.write("									<th>진로결정</th>\n");
      out.write("									<td>");
      out.print(level.get(2).getHigh_max());
      out.write("</td>\n");
      out.write("									<td><input name=\"setLevel\"\n");
      out.write("										value=");
      out.print(level.get(2).getHigh_max());
      out.write("></td>\n");
      out.write("									<td><input name=\"setLevel\"\n");
      out.write("										value=");
      out.print(level.get(2).getHigh_min());
      out.write("></td>\n");
      out.write("									<td><input name=\"setLevel\"\n");
      out.write("										value=");
      out.print(level.get(2).getNormal_max());
      out.write("></td>\n");
      out.write("									<td><input name=\"setLevel\"\n");
      out.write("										value=");
      out.print(level.get(2).getNormal_min());
      out.write("></td>\n");
      out.write("									<td><input name=\"setLevel\"\n");
      out.write("										value=");
      out.print(level.get(2).getLow_max());
      out.write("></td>\n");
      out.write("									<td><input name=\"setLevel\"\n");
      out.write("										value=");
      out.print(level.get(2).getLow_min());
      out.write("></td>\n");
      out.write("								</tr>\n");
      out.write("								<tr>\n");
      out.write("									<th>진로설계</th>\n");
      out.write("									<td>");
      out.print(level.get(3).getHigh_max());
      out.write("</td>\n");
      out.write("									<td><input name=\"setLevel\"\n");
      out.write("										value=");
      out.print(level.get(3).getHigh_max());
      out.write("></td>\n");
      out.write("									<td><input name=\"setLevel\"\n");
      out.write("										value=");
      out.print(level.get(3).getHigh_min());
      out.write("></td>\n");
      out.write("									<td><input name=\"setLevel\"\n");
      out.write("										value=");
      out.print(level.get(3).getNormal_max());
      out.write("></td>\n");
      out.write("									<td><input name=\"setLevel\"\n");
      out.write("										value=");
      out.print(level.get(3).getNormal_min());
      out.write("></td>\n");
      out.write("									<td><input name=\"setLevel\"\n");
      out.write("										value=");
      out.print(level.get(3).getLow_max());
      out.write("></td>\n");
      out.write("									<td><input name=\"setLevel\"\n");
      out.write("										value=");
      out.print(level.get(3).getLow_min());
      out.write("></td>\n");
      out.write("								</tr>\n");
      out.write("\n");
      out.write("								<tr>\n");
      out.write("									<th>경력개발</th>\n");
      out.write("									<td>");
      out.print(level.get(4).getHigh_max());
      out.write("</td>\n");
      out.write("									<td><input name=\"setLevel\"\n");
      out.write("										value=");
      out.print(level.get(4).getHigh_max());
      out.write("></td>\n");
      out.write("									<td><input name=\"setLevel\"\n");
      out.write("										value=");
      out.print(level.get(4).getHigh_min());
      out.write("></td>\n");
      out.write("									<td><input name=\"setLevel\"\n");
      out.write("										value=");
      out.print(level.get(4).getNormal_max());
      out.write("></td>\n");
      out.write("									<td><input name=\"setLevel\"\n");
      out.write("										value=");
      out.print(level.get(4).getNormal_min());
      out.write("></td>\n");
      out.write("									<td><input name=\"setLevel\"\n");
      out.write("										value=");
      out.print(level.get(4).getLow_max());
      out.write("></td>\n");
      out.write("									<td><input name=\"setLevel\"\n");
      out.write("										value=");
      out.print(level.get(4).getLow_min());
      out.write("></td>\n");
      out.write("								</tr>\n");
      out.write("\n");
      out.write("								<tr>\n");
      out.write("									<th>실무역량</th>\n");
      out.write("									<td>");
      out.print(level.get(5).getHigh_max());
      out.write("</td>\n");
      out.write("									<td><input name=\"setLevel\"\n");
      out.write("										value=");
      out.print(level.get(5).getHigh_max());
      out.write("></td>\n");
      out.write("									<td><input name=\"setLevel\"\n");
      out.write("										value=");
      out.print(level.get(5).getHigh_min());
      out.write("></td>\n");
      out.write("									<td><input name=\"setLevel\"\n");
      out.write("										value=");
      out.print(level.get(5).getNormal_max());
      out.write("></td>\n");
      out.write("									<td><input name=\"setLevel\"\n");
      out.write("										value=");
      out.print(level.get(5).getNormal_min());
      out.write("></td>\n");
      out.write("									<td><input name=\"setLevel\"\n");
      out.write("										value=");
      out.print(level.get(5).getLow_max());
      out.write("></td>\n");
      out.write("									<td><input name=\"setLevel\"\n");
      out.write("										value=");
      out.print(level.get(5).getLow_min());
      out.write("></td>\n");
      out.write("								</tr>\n");
      out.write("								<tr>\n");
      out.write("									<th>맞춤취업</th>\n");
      out.write("									<td>");
      out.print(level.get(6).getHigh_max());
      out.write("</td>\n");
      out.write("									<td><input name=\"setLevel\"\n");
      out.write("										value=");
      out.print(level.get(6).getHigh_max());
      out.write("></td>\n");
      out.write("									<td><input name=\"setLevel\"\n");
      out.write("										value=");
      out.print(level.get(6).getHigh_min());
      out.write("></td>\n");
      out.write("									<td><input name=\"setLevel\"\n");
      out.write("										value=");
      out.print(level.get(6).getNormal_max());
      out.write("></td>\n");
      out.write("									<td><input name=\"setLevel\"\n");
      out.write("										value=");
      out.print(level.get(6).getNormal_min());
      out.write("></td>\n");
      out.write("									<td><input name=\"setLevel\"\n");
      out.write("										value=");
      out.print(level.get(6).getLow_max());
      out.write("></td>\n");
      out.write("									<td><input name=\"setLevel\"\n");
      out.write("										value=");
      out.print(level.get(6).getLow_min());
      out.write("></td>\n");
      out.write("								</tr>\n");
      out.write("\n");
      out.write("								<tr>\n");
      out.write("									<th>구직활동</th>\n");
      out.write("									<td>");
      out.print(level.get(7).getHigh_max());
      out.write("</td>\n");
      out.write("									<td><input name=\"setLevel\"\n");
      out.write("										value=");
      out.print(level.get(7).getHigh_max());
      out.write("></td>\n");
      out.write("									<td><input name=\"setLevel\"\n");
      out.write("										value=");
      out.print(level.get(7).getHigh_min());
      out.write("></td>\n");
      out.write("									<td><input name=\"setLevel\"\n");
      out.write("										value=");
      out.print(level.get(7).getNormal_max());
      out.write("></td>\n");
      out.write("									<td><input name=\"setLevel\"\n");
      out.write("										value=");
      out.print(level.get(7).getNormal_min());
      out.write("></td>\n");
      out.write("									<td><input name=\"setLevel\"\n");
      out.write("										value=");
      out.print(level.get(7).getLow_max());
      out.write("></td>\n");
      out.write("									<td><input name=\"setLevel\"\n");
      out.write("										value=");
      out.print(level.get(7).getLow_min());
      out.write("></td>\n");
      out.write("								</tr>\n");
      out.write("\n");
      out.write("							</tbody>\n");
      out.write("						</table>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"setBtnDiv\">\n");
      out.write("						<input type=submit class=\"level_saveBtn\" value=\"저장\"> <input\n");
      out.write("							type=button class=\"level_exitBtn\" value=\"취소\">\n");
      out.write("					</div>\n");
      out.write("				</form>\n");
      out.write("				</seciont>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</main>\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "SitemapPopup.jsp", out, false);
      out.write('\n');
      out.write('	');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "LoginPopup.jsp", out, false);
      out.write("\n");
      out.write("	<script src=\"js/SitemapPopup.js\"></script>\n");
      out.write("	<script src=\"js/LoginPopup.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
