/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.82
 * Generated at: 2023-11-05 08:47:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class SitemapPopup_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1652609068539L));
    _jspx_dependants.put("jar:file:/C:/Users/82103/Final_Project/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/SNcp/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<div class=\"sitemap_popup\">\n");
      out.write("	<div class=\"sitemap_popup_body\">\n");
      out.write("		<div class=\"sitemap_wrapper\">\n");
      out.write("			<section class=\"sitemap_header\">\n");
      out.write("				<h2>전체메뉴</h2>\n");
      out.write("				<a class=\"sitemap_close\"></a>\n");
      out.write("			</section>\n");
      out.write("			<section class=\"sitemap_content\">\n");
      out.write("				<div class=\"sitemap_inner\">\n");
      out.write("					<div class=\"sitemap_list sitemap_list1\">\n");
      out.write("						<h2>SEMS+ 안내</h2>\n");
      out.write("						<ul>\n");
      out.write("							<li><a href=\"\">SEMS+ 소개</a></li>\n");
      out.write("							<li><a href=\"\">역량기반 교육체계</a></li>\n");
      out.write("							<li><a href=\"\">CUKI 마일리지</a></li>\n");
      out.write("						</ul>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"sitemap_list sitemap_list2\">\n");
      out.write("						<h2>역량기반교과</h2>\n");
      out.write("						<ul>\n");
      out.write("							<li><a href=\"\">교과 정보 조회</a></li>\n");
      out.write("							<li><a href=\"\">통합역량성취도 조회</a></li>\n");
      out.write("						</ul>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"sitemap_list sitemap_list3\">\n");
      out.write("						<h2>CUKI비교과</h2>\n");
      out.write("						<ul>\n");
      out.write("							<li><a href=\"\">비교과 프로그램 신청</a></li>\n");
      out.write("							<li><a href=\"\">비교과 프로그램 내역</a></li>\n");
      out.write("							<li><a href=\"\">자기주도활동</a></li>\n");
      out.write("						</ul>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"sitemap_list sitemap_list4\">\n");
      out.write("						<h2>상담</h2>\n");
      out.write("						<ul>\n");
      out.write("							<li><a href=\"\">사제동행상담</a></li>\n");
      out.write("							<li><a href=\"\">심리상담</a></li>\n");
      out.write("							<li><a href=\"\">진로 및 취·창업상담</a></li>\n");
      out.write("							<li><a href=\"\">학습상담</a></li>\n");
      out.write("							<li><a href=\"\">나의 상담 내역</a></li>\n");
      out.write("							<li><a href=\"\">성고충상담 안내</a></li>\n");
      out.write("						</ul>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"sitemap_list sitemap_list5\">\n");
      out.write("						<h2>진로/취업</h2>\n");
      out.write("						<ul>\n");
      out.write("							<li><a href=\"\">진로 설계</a></li>\n");
      out.write("							<li><a href=\"\">진로 디자인맵 조회</a></li>\n");
      out.write("							<li><a href=\"\">취업 정보</a></li>\n");
      out.write("							<li><a href=\"\">채용 정보</a></li>\n");
      out.write("							<li><a href=\"\">멘토링 프로그램</a></li>\n");
      out.write("							<li><a href=\"\">취업 지원 프로그램</a></li>\n");
      out.write("							<li><a href=\"\">취업 커뮤니티</a></li>\n");
      out.write("						</ul>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"sitemap_list sitemap_list6\">\n");
      out.write("						<h2>설문/진단</h2>\n");
      out.write("						<ul>\n");
      out.write("							<li><a href=\"\">전공역량 진단</a></li>\n");
      out.write("							<li><a href=\"CPTest.jsp\">진로개발준비도 검사</a></li>\n");
      out.write("							\n");
      out.write("						</ul>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"sitemap_list sitemap_list7\">\n");
      out.write("						<h2>인증</h2>\n");
      out.write("						<ul>\n");
      out.write("							<li><a href=\"\">내 역량 현황</a></li>\n");
      out.write("							<li><a href=\"\">내 인증 현황</a></li>\n");
      out.write("						</ul>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"sitemap_list sitemap_list8\">\n");
      out.write("						<h2>커뮤니티</h2>\n");
      out.write("						<ul>\n");
      out.write("							<li><a href=\"\">공지사항</a></li>\n");
      out.write("							<li><a href=\"\">갤러리</a></li>\n");
      out.write("							<li><a href=\"\">자료실</a></li>\n");
      out.write("							<li><a href=\"\">FAQ</a></li>\n");
      out.write("							<li><a href=\"\">쪽지</a></li>\n");
      out.write("						</ul>\n");
      out.write("					</div>\n");
      out.write("					<!-- 학생 접속 -->\n");
      out.write("					");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("					<!-- 교수 접속 -->\n");
      out.write("					");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("					<!-- 직원 접속 -->\n");
      out.write("					");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\n");
      out.write("					<!-- 슈퍼 유저 접속 -->\n");
      out.write("					");
      if (_jspx_meth_c_005fif_005f3(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\n");
      out.write("				</div>\n");
      out.write("			</section>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("</div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /SitemapPopup.jsp(85,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cookie.power.value eq '3' }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("						<div class=\"sitemap_list sitemap_list9\">\n");
          out.write("							<h2>마이페이지</h2>\n");
          out.write("							<ul>\n");
          out.write("								<li><a href=\"/mypage\">마이페이지</a></li>\n");
          out.write("								<li><a href=\"\">포트폴리오</a></li>\n");
          out.write("							</ul>\n");
          out.write("						</div>\n");
          out.write("					");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /SitemapPopup.jsp(95,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cookie.power.value eq '2' }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("						<div class=\"sitemap_list sitemap_list10\">\n");
          out.write("							<h2>교수</h2>\n");
          out.write("							<ul>\n");
          out.write("								<li><a href=\"Professor_Search_Student.jsp\">학생정보 조회</a></li>\n");
          out.write("							</ul>\n");
          out.write("						</div>\n");
          out.write("					");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent(null);
      // /SitemapPopup.jsp(104,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cookie.power.value eq '1' }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("						<div class=\"sitemap_list sitemap_list11\">\n");
          out.write("							<h2>관리자</h2>\n");
          out.write("							<ul>\n");
          out.write("								<li><a href=\"/ProgramManagement.jsp\">비교과 프로그램<br />관리\n");
          out.write("								</a></li>\n");
          out.write("								<li><a href=\"/Admin_mode.jsp\">역량 평가 설정<br />관리\n");
          out.write("								</a></li>\n");
          out.write("							</ul>\n");
          out.write("						</div>\n");
          out.write("					");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f3_reused = false;
    try {
      _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f3.setParent(null);
      // /SitemapPopup.jsp(116,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cookie.power.value eq '0' }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
      if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("						<div class=\"sitemap_list sitemap_list9\">\n");
          out.write("							<h2>마이페이지</h2>\n");
          out.write("							<ul>\n");
          out.write("								<li><a href=\"/mypage\">마이페이지</a></li>\n");
          out.write("								<li><a href=\"\">포트폴리오</a></li>\n");
          out.write("							</ul>\n");
          out.write("						</div>\n");
          out.write("						<div class=\"sitemap_list sitemap_list10\">\n");
          out.write("							<h2>교수</h2>\n");
          out.write("							<ul>\n");
          out.write("								<li><a href=\"/StudentManagement.jsp\">학생정보 조회</a></li>\n");
          out.write("								<li><a href=\"http://61.81.215.8:8080/Project_NCP/Professor_Search_Student_Servlet?professer=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cookie.number.value}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">학생 평가</a></li>\n");
          out.write("							</ul>\n");
          out.write("						</div>\n");
          out.write("						<div class=\"sitemap_list sitemap_list11\">\n");
          out.write("							<h2>관리자</h2>\n");
          out.write("							<ul>\n");
          out.write("								<li><a href=\"/ProgramManagement.jsp\">비교과 프로그램<br />관리\n");
          out.write("								</a></li>\n");
          out.write("							</ul>\n");
          out.write("						</div>\n");
          out.write("					");
          int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      _jspx_th_c_005fif_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f3_reused);
    }
    return false;
  }
}
